### ISSUE TITLE
Make the assets into Errors and Throw them with throws on the function

### ISSUE THREAD

**Issue by ajamaica** [metaplex-foundation/beet-swift#17]
**Is your feature request related to a problem? Please describe.**
The asserts don't allow further execution. We need to handle and send the error for apps to handle it.

**Describe the solution you'd like**
Remove the `assert()` and introduce `throws` on functions and `throw` with `if` stament

**Comment by staccDOTsol** [comment]
Sure, I can help you with that. Can you provide me with the code snippet where you want to replace the `assert()` with `throws` and `throw` statements?

**Comment by ajamaica** [comment]
I just finish it on [feature/throwable-states](https://github.com/metaplex-foundation/beet-swift/pull/18) @staccDOTsol Please help me if you want to review it.
